name: Maestro Cloud Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-tests:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Build .app
        run: |
          xcodebuild \
            -scheme "App" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            clean build
          
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          
      - name: Verify Maestro installation
        run: maestro --version
        
      - name: Run Maestro Cloud Tests
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
          MAESTRO_PROJECT_ID: ${{ secrets.MAESTRO_PROJECT_ID }}
        run: |
          maestro cloud \
            --api-key "$MAESTRO_API_KEY" \
            --project-id "$MAESTRO_PROJECT_ID" \
            "$GITHUB_WORKSPACE/build/Build/Products/Debug-iphonesimulator/App.app" \
            "$GITHUB_WORKSPACE/.maestro"